version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nilnil
    - prealloc
    - staticcheck
    - unparam
    - unused

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - linters:
          - errcheck
        text: "Error return value of `fmt\\.Fprint"
      - linters:
          - errcheck
        text: "Error return value of .*.Close"
      - linters:
          - staticcheck
        text: "QF1001"
